Update deploy-production.yml

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -30,7 +30,23 @@ jobs:
             if [ -d "${{ vars.APP_PROD_PATH }}" ]; then
               ssh-keyscan github.com >> ~/.ssh/known_hosts
               cd ${{ vars.APP_PROD_PATH }}
+              
+              # Show current release version
+              echo "Current Release Version:"
+              git describe --tags --always || echo "No tags found in git history"
+              
+              # Stop and remove only the 'pacmusic-prod' service
               sudo docker compose down pacmusic-prod
+              
+              # Optionally: remove related Docker images and volumes if you want to clean up
+              sudo docker image prune -f
+              sudo docker volume prune -f
+              sudo docker system prune -f
+
+              # Remove application directory (if needed, for cleanup)
+              sudo rm -rf ${{ vars.APP_PROD_PATH }}
+              
+              # Update the repo and pull latest changes
               git pull origin main
             else
               ssh-keyscan github.com >> ~/.ssh/known_hosts
