Update deploy-production.yml

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -13,6 +13,21 @@ jobs:
     environment: production
 
     steps:
+      # Step 0: Tunggu jika tag baru belum tersedia di registry Docker (jika menggunakan Docker Registry)
+      - name: Wait for Docker image tag to be available
+        run: |
+          APP_TAG="${{ env.TAG_NAME }}"
+          REGISTRY="docker.io"
+          APP_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/pacmusic"
+
+      # Cek apakah image dengan tag yang sesuai sudah tersedia di registry
+          echo "Waiting for Docker image ${APP_IMAGE}:${APP_TAG}..."
+          while ! curl --silent --fail "https://${REGISTRY}/v2/${APP_IMAGE}/manifests/${APP_TAG}" > /dev/null; do
+            echo "Image ${APP_IMAGE}:${APP_TAG} not found. Retrying in 30 seconds..."
+            sleep 30
+          done
+          echo "Image ${APP_IMAGE}:${APP_TAG} is now available."
+
       # Step 1: Checkout Repository
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -27,8 +42,8 @@ jobs:
           script: |
             # Check if APP_PROD_PATH exists
             if [ -d "${{ vars.APP_PROD_PATH }}" ]; then
+              cd "${{ vars.APP_PROD_PATH }}"
               ssh-keyscan github.com >> ~/.ssh/known_hosts
-              cd "${{ secrets.APP_PROD_PATH }}"
               sudo docker compose down pacmusic-prod
               git pull origin main
             else
